{"name": "Создание заказа с неверным хешем ингредиентов", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "self = <test_create_order.TestCreateOrder object at 0x106810e00>\n\n    @allure.title('Создание заказа с неверным хешем ингредиентов')\n    def test_create_order_with_invalid_hash(self):\n        user_body = UserData.generate_fake_user_data()\n        user = AuthResponses.create_user(user_body)\n        ingredients = Data.invalid_hash\n>       order = OrdersResponse.create_order(user, ingredients)\n\ntests/test_create_order.py:40: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nuser_response = <Response [403]>, ingredients = {'ingredients': [True]}\n\n    @staticmethod\n    @allure.step('Отправить запрос на создание заказа')\n    def create_order(user_response, ingredients):\n>       access_token = user_response.json()[\"accessToken\"]\nE       KeyError: 'accessToken'\n\nfunctions/orders_api.py:10: KeyError"}, "steps": [{"name": "Сгенерировать данные для пользователя", "status": "passed", "start": 1717960594349, "stop": 1717960594373}, {"name": "Отправить запрос на создание пользователя", "status": "passed", "parameters": [{"name": "user_body", "value": "{'email': 'michael40@example.net', 'password': '342503061', 'name': 'hollywheeler'}"}], "start": 1717960594373, "stop": 1717960594518}, {"name": "Отправить запрос на создание заказа", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'\n", "trace": "  File \"/Users/kseniagolovina/PycharmProjects/Diplom/Diplom2/.venv/lib/python3.12/site-packages/allure_commons/_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"/Users/kseniagolovina/PycharmProjects/Diplom/Diplom2/functions/orders_api.py\", line 10, in create_order\n    access_token = user_response.json()[\"accessToken\"]\n                   ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n"}, "parameters": [{"name": "user_response", "value": "<Response [403]>"}, {"name": "ingredients", "value": "{'ingredients': [True]}"}], "start": 1717960594518, "stop": 1717960594518}], "start": 1717960594348, "stop": 1717960594522, "uuid": "289e4d1a-be6b-420c-b4ec-801da287a7b2", "historyId": "7c1761ec96200ea376bf577bf0c946e2", "testCaseId": "7c1761ec96200ea376bf577bf0c946e2", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_hash", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_order"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "Xeniias-Laptop.local"}, {"name": "thread", "value": "35231-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}